"""
deterministic_embedder.cooccurrence_graph
-----------------------------------------

This module constructs a topological co‑occurrence graph from a corpus of
tokenised text.  Given a tokenizer specification (``tokenizer.json``) and
a directory of plain text files, it encodes the text into sequences of
integer token identifiers and computes token pair co‑occurrence counts using
a sliding window.  It also tracks the frequency of individual tokens.

The output of this module is two dictionaries:

* ``pair_counts``: a mapping ``(token_id_a, token_id_b) -> count`` that
  records how many times tokens ``a`` and ``b`` co‑occur within a
  fixed‑width window.
* ``token_counts``: a mapping ``token_id -> count`` that records how
  frequently each token appears in the corpus.

These counts can then be fed into subsequent processing stages to compute
Normalised Pointwise Mutual Information (NPMI) and build a sparse matrix.

Single responsibility: this module does not perform any PMI calculation or
matrix construction.  It solely maps raw text to statistical counts.
"""

from __future__ import annotations

import json
import os
from collections import Counter, defaultdict
from typing import Dict, Iterable, List, Sequence, Tuple


class BPETokenizer:
    """Minimal runtime BPE tokenizer for encoding words into tokens.

    This class reads a ``tokenizer.json`` generated by
    :class:`deterministic_embedder.tokenizer_trainer.BPETokenizerTrainer`
    and provides an ``encode`` method to convert text strings into
    sequences of integer token identifiers.

    The encoding algorithm applies merges greedily in the order they were
    learned during training.  Each input word is represented as a list of
    symbols (characters) with the end‑of‑word symbol appended, and
    merges are applied repeatedly until no more merge rules match.
    """

    def __init__(self, tokenizer_path: str) -> None:
        with open(tokenizer_path, "r", encoding="utf-8") as f:
            spec = json.load(f)
        self.vocab: Dict[str, int] = {k: int(v) for k, v in spec["vocab"].items()}
        # merges stored as list of lists or list of pairs; convert to tuples
        merges_raw = spec.get("merges", [])
        self.merges: List[Tuple[str, str]] = []
        for m in merges_raw:
            # Each merge may be stored as [a, b] or (a, b).  We normalise to tuple.
            if isinstance(m, list):
                self.merges.append((m[0], m[1]))
            elif isinstance(m, tuple):
                self.merges.append(m)
            else:
                # If it's a concatenated string, split the pair in two halves.
                # This is a fallback for accidental serialisation changes.
                half = len(m) // 2
                self.merges.append((m[:half], m[half:]))
        self.end_of_word: str = spec.get("end_of_word", "</w>")

    def _encode_word(self, word: str) -> List[str]:
        """Encode a single word into a list of BPE symbols (strings)."""
        # Initial symbol sequence: characters + end‑of‑word marker
        symbols: List[str] = list(word) + [self.end_of_word]
        # Apply merges greedily in the order they were learned
        for merge in self.merges:
            a, b = merge
            merged_token = a + b
            i = 0
            new_symbols: List[str] = []
            while i < len(symbols):
                if i < len(symbols) - 1 and symbols[i] == a and symbols[i + 1] == b:
                    new_symbols.append(merged_token)
                    i += 2
                else:
                    new_symbols.append(symbols[i])
                    i += 1
            symbols = new_symbols
        return symbols

    def encode(self, text: str) -> List[int]:
        """Encode a full text string into a list of token IDs.

        Splits text on whitespace, encodes each word separately, and
        concatenates the resulting token IDs.  Unknown tokens are mapped
        to a reserved ID ``-1``.  No padding or truncation is applied.

        Parameters
        ----------
        text: str
            The input text to encode.

        Returns
        -------
        List[int]
            A list of integer token IDs corresponding to the input text.
        """
        token_ids: List[int] = []
        for word in text.strip().split():
            symbols = self._encode_word(word)
            for sym in symbols:
                # Use vocab lookup; unknown symbols map to -1
                token_ids.append(self.vocab.get(sym, -1))
        return token_ids


def sliding_window_cooccurrence(
    token_stream: Iterable[int],
    window_size: int = 5,
) -> Tuple[Dict[Tuple[int, int], int], Dict[int, int]]:
    """Compute pair co‑occurrence counts and token frequencies from a token stream.

    Given an iterable of token IDs, this function slides a fixed‑width
    window over the sequence.  For each window it records all unordered
    pairs of token IDs within that window (excluding pairs where both
    positions are the same).  It also counts how often each individual
    token appears in the entire stream.

    Parameters
    ----------
    token_stream: Iterable[int]
        A sequence of integer token IDs.
    window_size: int, optional
        The size of the sliding window (default is 5).

    Returns
    -------
    pair_counts: Dict[Tuple[int, int], int]
        Mapping of unordered token ID pairs to their co‑occurrence count.
    token_counts: Dict[int, int]
        Mapping of token ID to its frequency in the stream.
    """
    # We'll implement an efficient sliding window using a deque
    from collections import deque

    window: deque[int] = deque([], maxlen=window_size)
    pair_counts: Dict[Tuple[int, int], int] = defaultdict(int)
    token_counts: Dict[int, int] = defaultdict(int)
    for token in token_stream:
        # Update token frequency
        token_counts[token] += 1
        # For each existing token in the window, update pair counts
        for existing_token in window:
            # Use ordered pair (min, max) for symmetry
            if token == existing_token:
                continue
            pair = (existing_token, token) if existing_token < token else (token, existing_token)
            pair_counts[pair] += 1
        # Slide the window forward
        window.append(token)
    return pair_counts, token_counts


def compute_counts(
    tokenizer_path: str,
    corpus_dir: str,
    window_size: int = 5,
) -> Tuple[Dict[Tuple[int, int], int], Dict[int, int]]:
    """Load a tokenizer and compute co‑occurrence statistics for a text corpus.

    This convenience function glues together the ``BPETokenizer`` and the
    ``sliding_window_cooccurrence`` function.  It reads all ``.txt`` files
    from ``corpus_dir``, encodes them into token IDs using the supplied
    tokenizer, concatenates the token streams (with implicit sentence
    boundaries being ignored), and then computes pair and token counts.

    Parameters
    ----------
    tokenizer_path: str
        Path to the JSON tokenizer specification produced by the trainer.
    corpus_dir: str
        Directory containing training text files.
    window_size: int, optional
        Width of the sliding window used for co‑occurrence counting.

    Returns
    -------
    pair_counts: Dict[Tuple[int, int], int]
        Mapping of unordered token pairs to counts.
    token_counts: Dict[int, int]
        Mapping of token IDs to frequencies.
    """
    tokenizer = BPETokenizer(tokenizer_path)
    pair_counts: Dict[Tuple[int, int], int] = defaultdict(int)
    token_counts: Dict[int, int] = defaultdict(int)
    # Read all files and accumulate token streams
    for root, _, files in os.walk(corpus_dir):
        for fname in files:
            if not fname.lower().endswith(".txt"):
                continue
            fpath = os.path.join(root, fname)
            try:
                with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                    for line in f:
                        # Encode line into token IDs
                        token_ids = tokenizer.encode(line)
                        # Update counts using sliding window
                        # For efficiency, call sliding_window_cooccurrence on each line
                        line_pair_counts, line_token_counts = sliding_window_cooccurrence(token_ids, window_size)
                        # Aggregate into global counts
                        for pair, cnt in line_pair_counts.items():
                            pair_counts[pair] += cnt
                        for token, cnt in line_token_counts.items():
                            token_counts[token] += cnt
            except OSError:
                continue
    return pair_counts, token_counts
