"""
deterministic_embedder.inference_engine
--------------------------------------

This module defines a runtime class for producing deterministic text
embeddings.  Given a JSON tokenizer specification and a pre‑computed
embedding matrix, it can encode arbitrary input strings into token IDs,
retrieve the corresponding token vectors, and compute a mean‑pooled
representation.

The returned artefact contains three keys:

* ``token_ids`` — the ordered list of integer IDs representing the
  verbatim text.  This allows perfect reconstruction of the tokenised
  input when combined with the tokenizer.
* ``token_vectors`` — a 2D numpy array of shape ``(n_tokens, k)`` where
  each row corresponds to the embedding vector of the token at that
  position in the input.
* ``pooled_vector`` — a 1D numpy array of length ``k`` that is the mean
  of ``token_vectors`` along the first axis.  This global semantic
  representation can be used for cosine similarity against other pooled
  vectors.

The interface is deliberately simple to satisfy the single concern rule: it
only performs text encoding and vector lookup.  It does not handle
training, co‑occurrence computation, PMI calculations, or SVD.  Those
concerns belong to other modules.
"""

from __future__ import annotations

import json
from typing import Dict, List

import numpy as np


class DeterministicEmbedder:
    """Runtime embedder for deterministic graph‑SVD embeddings."""

    def __init__(self, tokenizer_path: str, embeddings_path: str) -> None:
        """Initialise the embedder by loading the tokenizer and embeddings.

        Parameters
        ----------
        tokenizer_path: str
            Path to the JSON tokenizer specification.
        embeddings_path: str
            Path to a ``.npy`` file containing the embedding matrix
            generated by :func:`deterministic_embedder.spectral_compression.compute_embeddings`.
        """
        # Load tokenizer specification
        with open(tokenizer_path, "r", encoding="utf-8") as f:
            spec = json.load(f)
        # Ensure IDs are integers
        self.vocab: Dict[str, int] = {token: int(idx) for token, idx in spec["vocab"].items()}
        # Load merges for encoding
        merges_raw = spec.get("merges", [])
        self.merges: List[tuple[str, str]] = []
        for m in merges_raw:
            if isinstance(m, list):
                self.merges.append((m[0], m[1]))
            elif isinstance(m, tuple):
                self.merges.append(m)
            else:
                half = len(m) // 2
                self.merges.append((m[:half], m[half:]))
        self.end_of_word: str = spec.get("end_of_word", "</w>")
        # Load embeddings
        self.embeddings: np.ndarray = np.load(embeddings_path)
        # Validate dimensions
        if self.embeddings.ndim != 2:
            raise ValueError("Embeddings array must be 2D (vocab_size x dim)")
        # Unknown token ID mapping
        self.unknown_id: int = -1

    def _encode_word(self, word: str) -> List[str]:
        """Encode a single word into a list of BPE symbols."""
        symbols: List[str] = list(word) + [self.end_of_word]
        for a, b in self.merges:
            merged = a + b
            i = 0
            new_symbols: List[str] = []
            while i < len(symbols):
                if i < len(symbols) - 1 and symbols[i] == a and symbols[i + 1] == b:
                    new_symbols.append(merged)
                    i += 2
                else:
                    new_symbols.append(symbols[i])
                    i += 1
            symbols = new_symbols
        return symbols

    def _encode(self, text: str) -> List[int]:
        """Encode text into a list of token IDs."""
        token_ids: List[int] = []
        for word in text.strip().split():
            symbols = self._encode_word(word)
            for s in symbols:
                token_ids.append(self.vocab.get(s, self.unknown_id))
        return token_ids

    def embed_text(self, text: str) -> Dict[str, np.ndarray | List[int]]:
        """Embed a piece of text into deterministic vectors.

        Parameters
        ----------
        text: str
            The input string to embed.

        Returns
        -------
        Dict[str, Union[List[int], np.ndarray]]
            A dictionary containing ``token_ids``, ``token_vectors`` and
            ``pooled_vector``.
        """
        token_ids = self._encode(text)
        # Retrieve vectors; unknown tokens (ID -1) map to zero vectors
        dim = self.embeddings.shape[1]
        token_vectors: List[np.ndarray] = []
        for tid in token_ids:
            if 0 <= tid < len(self.embeddings):
                token_vectors.append(self.embeddings[tid])
            else:
                token_vectors.append(np.zeros(dim, dtype=self.embeddings.dtype))
        if token_vectors:
            token_vec_array = np.vstack(token_vectors)
            pooled_vec = token_vec_array.mean(axis=0)
        else:
            token_vec_array = np.zeros((0, self.embeddings.shape[1]), dtype=self.embeddings.dtype)
            pooled_vec = np.zeros(self.embeddings.shape[1], dtype=self.embeddings.dtype)
        return {
            "token_ids": token_ids,
            "token_vectors": token_vec_array,
            "pooled_vector": pooled_vec,
        }
